# Generated by Django 3.2.7 on 2021-11-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IDProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('Rubro', models.CharField(max_length=20)),
            ],
        ),
    ]
